- name: Copy xml file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://3.83.114.147:8080/
    user: admin